### ISSUE TITLE
Finalize implementation of the multiplication routines

### ISSUE THREAD

**Issue by AaronKutch** [Robbepop/apint#18]
Before I submit a pull request, should there be another branch or do I just use the master branch?

**Comment by Robbepop** [comment]
Ideally you implement new features on another branch than master since you then can use master to stay in sync with the origin/upstream master. It is just convention but if everybody sticks to conventions everything is easier.

**Comment by AaronKutch** [comment]
I attempted to do a pull request but there is a mixture of spaces and tabs being used which messes up the indentation. Do you want to use tabs because that's what it looks like you are using?

**Comment by Robbepop** [comment]
I personally use what is the default in the ecosystem.

I viewed your pull request but you have closed it already. You can `git push --force` your fork to overwrite bad states. This will automatically update the current pull request on GitHub. So you do not need to close it. Just re-open your PR, fix the stuff locally, `push --force` to your branch on GitHub and everything will be fine again. :)

Just one little question: Why have you used macros and macro invokations instead of simple plain functions?

**Comment by Robbepop** [comment]
I have recently looked into what is required by the implementation of karatsuba algorithm. It seems to be easily implementable but let's see. It is good to have your initial base implementation for medium size `ApInt` instances first so that I can check both implementations against each other later on.

**Comment by AaronKutch** [comment]
Ok I was planning on doing the renaming another pull request

**Comment by Robbepop** [comment]
That's a good idea! :) I might do the same.

**Comment by AaronKutch** [comment]
Because of out-of-date information here, I am continuing this in a new issue
