### ISSUE TITLE
Does this have no_std support?

### ISSUE THREAD

**Issue by drewstone** [Robbepop/apint#38]

**Comment by AaronKutch** [comment]
I can't remember if the current master branch or my `reorganization_rebase` branch works with no_std. I know that disabling all the default features removes the need for std, but you will have to try out my branch and open issues as they come. I have been waiting on Robbepop reviewing and accepting my PRs to get rid of some technical debt. Robbepop is quite busy and has not been able to review my latest refactor for a few months now. I should note that `apint` version 0.2.0 was released over a year ago, and there has been a bunch of breaking changes since then.

**Comment by AaronKutch** [comment]
When I get some free time later this week, I can enable and disable all the feature flags, and add an integration test to see if no_std works. However, too many commits are riding on my PR from the delays. Could someone other than Robbepop help review the "Refactor and update to edition 2018" PR, so I can move forward finally?

**Comment by AaronKutch** [comment]
Actually, now I remember that I just need to add a `no_std` flag so that the crate uses `core` instead of `std`. Would you like me to do this to the `reorganization_rebase` branch? The only user-facing problems I can remember is that there are warnings that I need to fix in upcoming PRs, I have not yet differentiated the `from_str_radix` and friends functions, and the rand dependency is really old and messes with `cargo doc`. I would update dependencies, but again I don't want to add much more to the commit tower.

**Comment by drewstone** [comment]
Thanks for the responses! It's not huge, I also don't have much bandwidth but am looking for number libraries with `no_std` support to maybe explore some cryptography in WASM. Will keep an eye on the work if I get a spare moment.

**Comment by Robbepop** [comment]
If I would write this library today I would design it as `no_std` from on the beginning.
Sadly this did not happen but I would really appreciate PRs for it. It is totally possible and should be done.

**Comment by Robbepop** [comment]
@drewstone optional `no_std` is going to be implemented by https://github.com/Robbepop/apint/pull/50. There is only one strange thing from blocking it.

**Comment by Robbepop** [comment]
Implemented. Closed.
